config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :matches

      resources :recipes

      resources :categories

      resources :chefs
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "categories#index"
  resources :matches
  resources :recipes
  resources :categories
  devise_for :chefs
  resources :chefs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord
  # Direct associations

  belongs_to :category,
             class_name: "Recipe"

  belongs_to :recipe,
             class_name: "Category"

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    category.to_s
  end
end

app/controllers/api/v1/matches_controller.rb
class Api::V1::MatchesController < Api::V1::GraphitiController
  def index
    matches = MatchResource.all(params)
    respond_with(matches)
  end

  def show
    match = MatchResource.find(params)
    respond_with(match)
  end

  def create
    match = MatchResource.build(params)

    if match.save
      render jsonapi: match, status: :created
    else
      render jsonapi_errors: match
    end
  end

  def update
    match = MatchResource.find(params)

    if match.update_attributes
      render jsonapi: match
    else
      render jsonapi_errors: match
    end
  end

  def destroy
    match = MatchResource.find(params)

    if match.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: match
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: %i[show edit update destroy]

  def index
    @q = Match.ransack(params[:q])
    @matches = @q.result(distinct: true).includes(:recipe,
                                                  :category).page(params[:page]).per(10)
  end

  def show; end

  def new
    @match = Match.new
  end

  def edit; end

  def create
    @match = Match.new(match_params)

    if @match.save
      message = "Match was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @match, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @match.update(match_params)
      redirect_to @match, notice: "Match was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @match.destroy
    message = "Match was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to matches_url, notice: message
    end
  end

  private

  def set_match
    @match = Match.find(params[:id])
  end

  def match_params
    params.require(:match).permit(:category_id, :recipe_id)
  end
end

app/views/matches/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Match #<%= match.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Category</dt>
      <dd>
        <% if @match.category.present? %>
          <%= link_to match.category, match.category %>
        <% end %>
      </dd>

      <dt>Recipe</dt>
      <dd>
        <% if @match.recipe.present? %>
          <%= link_to match.recipe, match.recipe %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back match, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_match_url(match), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to match, method: :delete, data: { confirm: "Do you really want to delete this match?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(match.updated_at) %> ago
  </div>
</div>

app/views/matches/_form.html.erb
<% was_validated = match.errors.any? %>

<%= form_with(model: match, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% category_class = "form-control" %>
    <% category_was_invalid = match.errors.include?(:category) %>

    <% if was_validated %>
      <% if category_was_invalid %>
        <% category_class << " is-invalid" %>
      <% else %>
        <% category_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Recipe.all, :id, :to_s, {}, class: "form-control" %>
    <% if category_was_invalid %>
      <% match.errors.full_messages_for(:category).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% recipe_class = "form-control" %>
    <% recipe_was_invalid = match.errors.include?(:recipe) %>

    <% if was_validated %>
      <% if recipe_was_invalid %>
        <% recipe_class << " is-invalid" %>
      <% else %>
        <% recipe_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :recipe_id %>
    <%= f.collection_select :recipe_id, Category.all, :id, :to_s, {}, class: "form-control" %>
    <% if recipe_was_invalid %>
      <% match.errors.full_messages_for(:recipe).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/matches/_list_item.html.erb
<%= link_to match, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= match %>
    <small class="text-muted">
      <%= time_ago_in_words(match.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/matches/_matches_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "matches_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :recipe_category_name_cont, "Recipe category_name contains" %>
    <%= f.text_field :recipe_category_name_cont, :class => "form-control", :placeholder => "Recipe category_name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :category_recipe_name_cont, "Category recipe_name contains" %>
    <%= f.text_field :category_recipe_name_cont, :class => "form-control", :placeholder => "Category recipe_name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/matches" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#matches_filters">
  Show filters
</a>

app/views/matches/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Match #<%= @match.id %>
      </h2>

      <div class="card-body">
        <%= render "form", match: @match %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/matches/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Matches

      <%= link_to new_match_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "matches/matches_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Matches

        <%= link_to new_match_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @matches, partial: "list_item", as: :match %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @matches, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/matches/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Match
      </h2>

      <div class="card-body">
        <%= render "form", match: @match %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/matches/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @match, partial: "card", as: :match %>
  </div>
</div>